# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pa-test-internal-testserver-app

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    branches:
      - develop
      - test/ci
jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: test

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: jfrog-central
        server-username: INTERNAL_USERNAME
        server-password: INTERNAL_PASSWORD
        cache: maven
    - name: Package test server war
      run: |
        cd powerauth-test-server
        mvn package
      env:
        # those are not environmental secrect, but global secret - for readonly access to artifactory
        INTERNAL_USERNAME: ${{ secrets.JFROG_USERNAME }}
        INTERNAL_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://powerauthextendedtest.azurecr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: powerauthextendedtest.azurecr.io/powerauth-test-server:${{ github.sha }}
        file: ./powerauth-test-server/Dockerfile
        context: ./powerauth-test-server/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pa-test-internal-testserver-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f6e36b4b50bd4835a473961ea7b7878c }}
        images: 'powerauthextendedtest.azurecr.io/powerauth-test-server:${{ github.sha }}'
