name: Test with Maven

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: environment
        default: dev
        options:
          - dev
  schedule:
    - cron: '0 0 * * *'

jobs:
  maven-tests:
    uses: wultra/wultra-infrastructure/.github/workflows/maven-test.yml@develop
    secrets: inherit
    environment: ${{ inputs.environment || 'dev' }}
    env:
      POWERAUTH_REST_URL: ${{ env.POWERAUTH_REST_URL }}
      POWERAUTH_INTEGRATION_SERVICE_URL: ${{ env.POWERAUTH_INTEGRATION_SERVICE_URL }}
      POWERAUTH_NEXTSTEP_SERVICE_URL: ${{ env.POWERAUTH_NEXTSTEP_SERVICE_URL }}
      POWERAUTH_ENROLLMENT_SERVICE_URL: ${{ env.POWERAUTH_ENROLLMENT_SERVICE_URL }}
      POWERAUTH_ENROLLMENT_ONBOARDING_SERVICE_URL: ${{ env.POWERAUTH_ENROLLMENT_ONBOARDING_SERVICE_URL }}
      POWERAUTH_SERVICE_SECURITY_CLIENTTOKEN: ${{ secrets.POWERAUTH_SERVICE_SECURITY_CLIENTTOKEN }}
      POWERAUTH_SERVICE_SECURITY_CLIENTSECRET: ${{ secrets.POWERAUTH_SERVICE_SECURITY_CLIENTSECRET }}
    with:
      directory_path: powerauth-backend-tests
