name: Integration Test with Maven

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: environment
        default: 'dev'
        options:
          - dev
      includeCustomTests:
        type: boolean
        description: Set whether to include custom tests, such as onboarding tests and test requiring specific customizations in enrollment-server-wultra
        default: true
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'dev' }}
    steps:
      - name: Log runner IP and region
        run: |
          echo "Public IP:"
          curl -s https://ifconfig.me
          echo -e "\nRegion info (GeoIP):"
          curl -s https://ipinfo.io
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          server-id: jfrog-central
          server-username: INTERNAL_USERNAME
          server-password: INTERNAL_PASSWORD
          cache: maven
      - name: Run Maven Test Step
        run: |
          mvn -B -U -pl powerauth-backend-tests test -DuseInternalRepo=true
        env:
          INTERNAL_USERNAME: ${{ secrets.JFROG_USERNAME }}
          INTERNAL_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          POWERAUTH_REST_URL: ${{ secrets.POWERAUTH_REST_URL }}
          POWERAUTH_INTEGRATION_SERVICE_URL: ${{ secrets.POWERAUTH_INTEGRATION_SERVICE_URL }}
          POWERAUTH_ENROLLMENT_SERVICE_URL: ${{ secrets.POWERAUTH_ENROLLMENT_SERVICE_URL }}
          POWERAUTH_ENROLLMENT_ONBOARDING_SERVICE_URL: ${{ secrets.POWERAUTH_ENROLLMENT_ONBOARDING_SERVICE_URL }}
          POWERAUTH_SERVICE_SECURITY_CLIENTTOKEN: ${{ secrets.POWERAUTH_SERVICE_SECURITY_CLIENTTOKEN }}
          POWERAUTH_SERVICE_SECURITY_CLIENTSECRET: ${{ secrets.POWERAUTH_SERVICE_SECURITY_CLIENTSECRET }}
          POWERAUTH_TEST_INCLUDECUSTOMTESTS: ${{ inputs.includeCustomTests == '' || inputs.includeCustomTests }} # default includeCustomTests=true even for 'schedule' event
          POWERAUTH_TEST_ACTIVATION_OIDC_USERNAME: ${{ secrets.POWERAUTH_TEST_ACTIVATION_OIDC_USERNAME }}
          POWERAUTH_TEST_ACTIVATION_OIDC_PASSWORD: ${{ secrets.POWERAUTH_TEST_ACTIVATION_OIDC_PASSWORD }}
          POWERAUTH_TEST_ACTIVATION_OIDC_PROVIDERID: ${{ secrets.POWERAUTH_TEST_ACTIVATION_OIDC_PROVIDERID }}
          POWERAUTH_TEST_ACTIVATION_OIDC_SUB: ${{ secrets.POWERAUTH_TEST_ACTIVATION_OIDC_SUB }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          detailed_summary: true
          report_paths: '**/target/surefire-reports/*.xml'
