name: Test with Maven

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment
        default: dev
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  maven-tests:
    uses: wultra/wultra-infrastructure/.github/workflows/maven-test.yml@develop
    secrets: inherit
    environment: ${{ inputs.environment }}
    with:
      directory_path: powerauth-backend-tests
