name: Deploy with Maven

on:
  workflow_dispatch:
    branches:
      - 'develop'
      - 'master'
      - 'releases/*'

jobs:
  maven-deploy-manual-test-server:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Manual deploy test-server
    uses: wultra/wultra-infrastructure/.github/workflows/maven-deploy.yml@develop
    with:
      environment: internal-publish
      release_type: snapshot
      directory_path: ./powerauth-test-server
      java_version: 21
    secrets:
      username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}


  maven-deploy-manual-fido2-tests:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Manual deploy firo2-tests
    uses: wultra/wultra-infrastructure/.github/workflows/maven-deploy.yml@develop
    with:
      environment: internal-publish
      release_type: snapshot
      directory_path: ./powerauth-fido2-tests
      java_version: 21
    secrets:
      username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}