name: Test Compile with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'releases/**'


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: jfrog-central
          server-username: INTERNAL_USERNAME
          server-password: INTERNAL_PASSWORD
          cache: maven
      - name: Run Maven Test-Compile Step
        run: |
          mvn -B -U test-compile -DuseInternalRepo=true
        env:
          # those are not environmental secret, but global secret - for readonly access to artifactory, credentials has to be passed this way
          INTERNAL_USERNAME: ${{ secrets.JFROG_USERNAME }}
          INTERNAL_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          BRANCH: ${{ github.ref_name }}
