
# PowerAuth service configuration
powerauth.service.baseUrl=${FIDO2_DEMO_PAS_BASE_URL:http://localhost:8080/powerauth-java-server}
powerauth.service.applicationId=${FIDO2_DEMO_PAS_APP_ID:}
powerauth.service.security.clientToken=${FIDO2_DEMO_PAS_CLIENT_TOKEN:}
powerauth.service.security.clientSecret=${FIDO2_DEMO_PAS_CLIENT_SECRET:}

# WebAuthn properties configuration
powerauth.webauthn.rpId=${FIDO2_DEMO_RP_ID:}
powerauth.webauthn.rpName=${FIDO2_DEMO_RP_NAME:}
powerauth.webauthn.timeout=60s
powerauth.webauthn.allowedOrigins=${FIDO2_DEMO_ALLOWED_ORIGINS:}
powerauth.webauthn.allowedTopOrigins=${FIDO2_DEMO_ALLOWED_TOP_ORIGINS:}

# Application Service Configuration
powerauth.fido2.test.service.applicationName=powerauth-fido2-tests
powerauth.fido2.test.service.applicationDisplayName=PowerAuth FIDO2 Test
powerauth.fido2.test.service.applicationEnvironment=
powerauth.fido2.test.service.hideDeveloperOptions=${FIDO2_DEMO_HIDE_OPTIONS:false}
powerauth.fido2.test.service.emailAddressRequired=${FIDO2_DEMO_EMAIL_REQUIRED:false}

banner.application.name=${powerauth.fido2.test.service.applicationName}
banner.application.version=@project.version@

# Disable JS caching
spring.web.resources.cache.cachecontrol.no-store=true

# To correctly handle redirection
server.forward-headers-strategy=framework

# To avoid having JSESSIONID in URI
server.servlet.session.tracking-modes=cookie

# Handle cookies in iFrame
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

# Logging configuration
logging.level.root=INFO
logging.config=${FIDO2_DEMO_LOGGING:}
